config/routes.rb
GameApplication::Application.routes.draw do
 
  get "gamers/index"

  get "gamers/show"

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"

  resources :games

  devise_for :admins

  devise_for :gamers

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/game.rb
class Game < ActiveResource::Base
  
  self.site = "http://localhost:2000"
  
  schema do
      attribute 'gamer_id', 'integer'
      attribute 'score', 'integer'
    end
    
    validates_presence_of :gamer_id, :score
  
end

app/models/gamer.rb
class Gamer < ActiveRecord::Base
  
  validates_presence_of :name
  validates_uniqueness_of :name, :email, :case_sensitive => false
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  def games
    Game.find(:all, :from => :find_by_gamer_id, :params =>{:gamer_id => self.id})
  end
  
  def top_ten_scores
    games.sort(&:score).reverse.slice!(0..9)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/gamers_controller.rb
class GamersController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter :authenticate_gamer!
  # GET /games
  # GET /games.json
  def index
    @games = Game.find(:all)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(params[:game])
    @game.gamer_id = current_gamer.id
    
    respond_to do |format|
      if @game.save
        format.html { redirect_to :root }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @gamers = Gamer.all
    if !Game.all.empty?
      @top_ten_high_score_list = Game.all.sort_by(&:score).reverse.slice!(0..9)
    end
    if current_gamer
      @top_ten_user_high_score_list = Game.find(:all, :from => :find_by_gamer_id, 
        :params => {:gamer_id => current_gamer.id}).sort_by(&:score).reverse.slice!(0..9)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def standard_date(date)
    date.strftime("%B %d, %Y")
  end
  
end

app/helpers/gamers_helper.rb
module GamersHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/gamers/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/gamers/index.html.erb
<h1>Gamers#index</h1>
<p>Find me in app/views/gamers/index.html.erb</p>

app/views/gamers/show.html.erb
<h1>Gamers#show</h1>
<p>Find me in app/views/gamers/show.html.erb</p>

app/views/games/_form.html.erb
<%= form_for(@game) do %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= label_tag :score %><br />
    <%= number_field_tag "game[score]" %>
	<%= hidden_field_tag "gamer_id[current_gamer.id]"%>
  </div>
  <div class="actions">
    <%= submit_tag 'submit', :game => @game %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @games.each do |game| %>
  <tr>
    <td><%= link_to 'Show', game %></td>
    <td><%= link_to 'Edit', edit_game_path(game) %></td>
    <td><%= link_to 'Destroy', game, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>



<%= render 'form' %>

<%= link_to "Back to main page", :root %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/home/index.html.erb
<div class="center">
	
	<h1>Welcome to the Game Application</h1>

	<h2>Our Top 10 High Scores List</h2>
	
	<% if @top_ten_high_score_list.blank? %>
		<h4>We need gamers! sign up today</h4>
	<% else %>
		<table class="center">
		  <tr>
			<th>Gamer Name</th>
		    <th>Gamer Score</th>
		    <th>Date</th>
		  </tr>
		<% @top_ten_high_score_list.each do |game| %>
		  <tr>
			<td><%= Gamer.find_by_id(game.gamer_id).name %></td>
			<td><%= number_with_delimiter game.score %></td>
			<td><%= standard_date game.created_at.to_date %></td>
		  </tr>
		<% end %>
		</table>
	<% end %>
	
	<% if gamer_signed_in? && !@top_ten_user_high_score_list.blank? %>
		<h2><%= current_gamer.name %>'s Top 10 High Scores List</h2>
			<table class="center">
			  <tr>
				<th>Gamer Name</th>
			    <th>Gamer Score</th>
			    <th>Date</th>
			  </tr>
			<% @top_ten_user_high_score_list.each do |game| %>
			  <tr>
				<td><%= Gamer.find_by_id(game.gamer_id).name %></td>
				<td><%= number_with_delimiter game.score %></td>
				<td><%= standard_date game.created_at.to_date %></td>
			  </tr>
			<% end %>
		</table>
	<% end %>
	
	<% if gamer_signed_in? %>
	</div>
		<div class="user">
		  <h4>Hello <%= current_gamer.name %></h4>
			<p>Click here to 
			<%= link_to 'Enter a score', new_game_path %>
			</p>
			<p>Click here to 
		  <%= link_to('Logout', destroy_gamer_session_path, :method => :delete) %>        
		  </p>
		</div>
	<% else %>
		<h4>Not a member? sign up for free
		<%= link_to('Register', new_gamer_registration_path)%>
		</h4>
		<h4>Otherwise Please login
		 <%= link_to('Login', new_gamer_session_path)  %>
		</h4>
	</div>
	<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GameApplication</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>